POST http://localhost:3001/api/lists/
Content-Type: application/json
Authorization: bearer <token here>

{
    "name": "ostoslista2",
    "items": [
        {
            "name": "makkara",
            "quantity": 2
        },
        {
            "name": "farkut",
            "quantity": 1
        }
    ]
}