PUT http://localhost:3001/api/lists/5eca87882ce5623f0444001d
Content-Type: application/json
Authorization: bearer <token here>

{
  "items": [
    {
      "item": "makkara",
      "quantity": 2,
      "date": null
    },
    {
      "item": "farkut",
      "quantity": 1,
      "date": "2020-05-24T14:41:12.537Z"
    }
  ],
  "name": "ostoslista2",
  "created": "2020-05-24T14:41:12.537Z",
  "default": false,
  "active": true,
  "id": "5eca87882ce5623f0444001d"
}